config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'ilovetocode' => 'states#index'

  get 'contact' => 'welcome#contact'
  get 'about' => 'welcome#about'

  resources :activities
  resources :states

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
    @pictures = ["beach-scoot.jpg","hiking.jpg","skiing.jpg","land-rover.jpg"]
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :cost, :duration)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :capital, :population)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
    @color = params[:color]
    @colorpad = {"danger"=>"red","warning"=>"yellow","success"=>"green","primary"=>"blue"}
  end

  def about
  	
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="abel">Listing Activities</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Cost</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.id %></td>
        <td><%= activity.name %></td>
        <td><%= number_to_currency activity.cost %></td>
        <td><%= distance_of_time_in_words(activity.duration*3600) %></td>
        <td><span class="glyphicon glyphicon-eye-open"></span> <%= link_to 'Show', activity %></td>
        <td><span class="glyphicon glyphicon-pencil"></span> <%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><span class="glyphicon glyphicon-remove"></span> <%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'New Activity', new_activity_path, class: "btn btn-info" %>
</p>

<hr />

<div class="center-it">
  <% @pictures.shuffle.each do |pic| %>
    <%= image_tag pic, alt: "adventures", width: "400" %>
  <% end %>
</div>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @activity.cost %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @activity.duration %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>What Time Is It?</title>
  <!-- Latest compiled and minified CSS -->
	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", integrity: "sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7", crossorigin:"anonymous" %>

	<link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "States", states_path %></li>
          <li><%= link_to "Activities", activities_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contact <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Red Version", contact_path(color: "red") %></li>
              <li><%= link_to "Blue Version", contact_path(color: "blue") %></li>
              <li><%= link_to "Green Version", contact_path(color: "green") %></li>
              <li><%= link_to "Yellow Version", contact_path(color: "yellow") %></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


	<div class="container">
		<%= yield %>
	</div>

  <!-- Latest compiled and minified JavaScript -->
	<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js", integrity: "sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS", crossorigin:"anonymous" %>
</body>
</html>

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :capital %><br>
    <%= f.text_field :capital %>
  </div>
  <div class="field">
    <%= f.label :population %><br>
    <%= f.number_field :population %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="abel">Listing States</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Capital</th>
      <th>Population</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.id %></td>
        <td><%= state.name %></td>
        <td><%= state.capital %></td>
        <td><%= number_with_delimiter state.population %></td>
        <td><span class="glyphicon glyphicon-eye-open"></span> <%= link_to 'Show', state %></td>
        <td><span class="glyphicon glyphicon-pencil"></span> <%= link_to 'Edit', edit_state_path(state) %></td>
        <td><span class="glyphicon glyphicon-remove"></span> <%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path, class: "btn btn-info"  %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Capital:</strong>
  <%= @state.capital %>
</p>

<p>
  <strong>Population:</strong>
  <%= @state.population %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>

app/views/welcome/about.html.erb
<h1>Whatever</h1>

app/views/welcome/contact.html.erb
<style>
  .chameleon-text {
    color: <%= @color %>;
  }
</style>

<div class="center-it">
  <h1>Contact Me, Bro!</h1>

  <p>
    <%= image_tag "camels.jpg", alt: "CAMELS!", width: "500" %>
  </p>
  <p class="chameleon-text">
    Sriracha messenger bag marfa fashion axe tousled, tumblr vegan etsy drinking vinegar crucifix man braid kickstarter cronut paleo. Lo-fi schlitz cray, scenester mlkshk actually echo park yuccie chartreuse tattooed. Pour-over hammock pork belly asymmetrical. Post-ironic vegan schlitz mlkshk, waistcoat farm-to-table echo park cardigan tattooed. Taxidermy synth direct trade heirloom, migas tote bag tousled flexitarian master cleanse cronut poutine blue bottle 90's. Listicle butcher seitan man bun, keytar squid helvetica. Taxidermy tumblr cred artisan, four dollar toast hashtag echo park pinterest meggings twee.
  </p>

  <h2>Change the Color of the Paragraph!</h2>

  <!-- Show only buttons for colors that are currently the background -->
  <% @colorpad.each do |k,v| %>
    <% if @color != v %>
        <%= link_to "#{v.capitalize}", contact_path(color: v), class: "btn btn-#{k}" %>
    <% end %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="center-it">
  <h1 class="abel">Adventures!</h1>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <p>
        Whatya building? Uhm, its just a little stick fort. Oh, rad! Look. Its just my size. Hey, get away from my fort, you big stinky monster! I like it when you get small, Jake. Yeah, me too. Whoa, whoa!
      </p>
      <p>
        Oh, dude. There's a note. What's it say? Hey, guys, I had to run out, but I'll be back, blee-bloo-blop, Don't go in my house. That's it? Yeah. Just Don't go in my house in all caps... written in blood.
      </p>
    </div>
  </div>
</div>